id: P000622
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W26004
  title: གནམ་འོག་གི་འཇིག་རྟེན
  author: ''
  volumes:
    9ebf0a13984647a8b61c7073cba52022:
      image_group_id: I1CZ2848
      title: ''
      volume_number: 1
      total_pages: 310
